baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hello-friend-ng"

paginate = 10
enableRobotsTXT = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Android app, custom kernel, and chatbot developer"
  description = "Personal website and blog of kdrag0n, an Android app, custom kernel, and chatbot developer."
  keywords = "kdrag0n, homepage, blog"
  images = [""]

  enableSharingButtons = true

  [params.portrait]
    path     = "/img/avatar.png"
    alt      = "Avatar"
    maxWidth = "50px"

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/kdrag0n"

  [[params.social]]
    name = "email"
    url  = "mailto:danny@kdrag0n.dev"

  [[params.social]]
    name = "github"
    url  = "https://github.com/kdrag0n"

  [[params.social]]
    name = "telegram"
    url  = "https://t.me/kdrag0n"

[languages]
  [languages.en]
    title = "Danny Lin"
    keywords = ""
    copyright = 'CC BY-NC 4.0'
    readOtherPosts = "Read other posts"

    # Ideally this would be removed entirely, but the theme doesn't support that
    footerLeft = "Made with &#10084;"
    # For license compliance
    footerRight = "Theme by Djordje Atlialp"

    [languages.en.params.logo]
      logoMark = ">"
      logoText = "kdrag0n"
      logoHomeLink = "/"
      # Disable distracting animation
      logoCursorDisabled = true

[menu]
  #[[menu.main]]
  #  identifier = "downloads"
  #  name       = "Downloads"
  #  url        = "/files"

  #[[menu.main]]
  #  identifier = "donate"
  #  name       = "Donate"
  #  url        = "/donate"

  #[[menu.main]]
  #  identifier = "blog"
  #  name       = "Blog"
  #  url        = "/posts"

  #[[menu.main]]
  #  identifier = "about"
  #  name       = "About"
  #  url        = "/about"
