baseURL = "https://kdrag0n.dev/"
languageCode = "en-us"
title = "kdrag0n"
theme = "hello-friend-ng"

paginate = 10
disableHugoGeneratorInject = true

[minify]
  minifyOutput = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Android & web developer"
  description = "Personal website and blog of kdrag0n, an Android and web developer."
  keywords = "kdrag0n, homepage, blog"
  images = [""]

  enableSharingButtons = true

  [params.portrait]
    path     = "/img/avatar.png"
    alt      = "Avatar"
    maxWidth = "50px"

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/kdrag0n"

  [[params.social]]
    name = "email"
    url  = "mailto:hi+websocial@kdrag0n.dev"

  [[params.social]]
    name = "github"
    url  = "https://github.com/kdrag0n"

  [[params.social]]
    name = "telegram"
    url  = "https://t.me/kdrag0n"

  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@kdrag0n:matrix.org"

  [[params.social]]
    name = "patreon"
    url  = "https://patreon.com/kdrag0n"

[languages]
  [languages.en]
    title = "Danny Lin"
    keywords = ""
    copyright = 'CC BY-NC 4.0'
    readOtherPosts = "Read other posts"

    # Ideally this would be removed entirely, but the theme doesn't support that
    footerLeft = '<a href="/terms-of-service">Terms</a> · <a href="/privacy-policy">Privacy</a> · <a href="https://stats.uptimerobot.com/QLkLLS6KYE">Status</a>'
    # For license compliance
    footerRight = "Theme by Djordje Atlialp"

    [languages.en.params.logo]
      logoMark = ">"
      logoText = "kdrag0n"
      logoHomeLink = "/"
      # Disable distracting animation
      logoCursorDisabled = true

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 1000

  [[menu.main]]
    identifier = "releases"
    name       = "Releases"
    url        = "/patreon"
    weight     = -100

  #[[menu.main]]
  #  identifier = "blog"
  #  name       = "Blog"
  #  url        = "/posts"
